<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="57536" started-at="2019-03-23T19:45:53Z" finished-at="2019-03-23T19:46:50Z">
    <groups>
    </groups>
    <test name="Test-Login restricted/unrestricted" duration-ms="27725" started-at="2019-03-23T19:45:53Z" finished-at="2019-03-23T19:46:20Z">
      <class name="Academy.HomePage">
        <test-method status="PASS" signature="initialize()[pri:0, instance:Academy.HomePage@c03cf28]" name="initialize" is-config="true" duration-ms="3521" started-at="2019-03-23T19:45:53Z" finished-at="2019-03-23T19:45:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="baseNavigate(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Academy.HomePage@c03cf28]" name="baseNavigate" duration-ms="18594" started-at="2019-03-23T19:45:56Z" data-provider="getData" finished-at="2019-03-23T19:46:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[email@email.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[restricted]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- baseNavigate -->
        <test-method status="PASS" signature="baseNavigate(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Academy.HomePage@c03cf28]" name="baseNavigate" duration-ms="5478" started-at="2019-03-23T19:46:15Z" data-provider="getData" finished-at="2019-03-23T19:46:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[non-restricted@restrict.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password24]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[non-restricted]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- baseNavigate -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Academy.HomePage@c03cf28]" name="tearDown" is-config="true" duration-ms="99" started-at="2019-03-23T19:46:20Z" finished-at="2019-03-23T19:46:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Academy.HomePage -->
    </test> <!-- Test-Login restricted/unrestricted -->
    <test name="Test Validate titles" duration-ms="13972" started-at="2019-03-23T19:46:20Z" finished-at="2019-03-23T19:46:34Z">
      <class name="Academy.validateTitle">
        <test-method status="PASS" signature="initialize()[pri:0, instance:Academy.validateTitle@d6e7bab]" name="initialize" is-config="true" duration-ms="2288" started-at="2019-03-23T19:46:20Z" finished-at="2019-03-23T19:46:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="baseNavigate()[pri:0, instance:Academy.validateTitle@d6e7bab]" name="baseNavigate" duration-ms="8632" started-at="2019-03-23T19:46:23Z" finished-at="2019-03-23T19:46:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [FEATURED COURSES12] but found [FEATURED COURSES]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [FEATURED COURSES12] but found [FEATURED COURSES]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Academy.validateTitle.baseNavigate(validateTitle.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- baseNavigate -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Academy.validateTitle@d6e7bab]" name="tearDown" is-config="true" duration-ms="2097" started-at="2019-03-23T19:46:32Z" finished-at="2019-03-23T19:46:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Academy.validateTitle -->
    </test> <!-- Test Validate titles -->
    <test name="Test validate navigation bar" duration-ms="15751" started-at="2019-03-23T19:46:34Z" finished-at="2019-03-23T19:46:50Z">
      <class name="Academy.validateNavBar">
        <test-method status="PASS" signature="initialize()[pri:0, instance:Academy.validateNavBar@503d687a]" name="initialize" is-config="true" duration-ms="2280" started-at="2019-03-23T19:46:34Z" finished-at="2019-03-23T19:46:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="baseNavigate()[pri:0, instance:Academy.validateNavBar@503d687a]" name="baseNavigate" duration-ms="9968" started-at="2019-03-23T19:46:37Z" finished-at="2019-03-23T19:46:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at Academy.validateNavBar.baseNavigate(validateNavBar.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- baseNavigate -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Academy.validateNavBar@503d687a]" name="tearDown" is-config="true" duration-ms="2078" started-at="2019-03-23T19:46:48Z" finished-at="2019-03-23T19:46:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Academy.validateNavBar -->
    </test> <!-- Test validate navigation bar -->
  </suite> <!-- Suite -->
</testng-results>
